// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTeDXtXNaQ19PQ3vzg3w43NR3tfItyIb8',
    appId: '1:573494420709:web:07496e5228bd32e165600c',
    messagingSenderId: '573494420709',
    projectId: 'imagelabeling-94220',
    authDomain: 'imagelabeling-94220.firebaseapp.com',
    storageBucket: 'imagelabeling-94220.firebasestorage.app',
    measurementId: 'G-18HLSYK8KF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsj7yETbVNgkV9v7Rwypvsy0MhIGMZPlA',
    appId: '1:573494420709:android:b0a6d70ab2cfd67465600c',
    messagingSenderId: '573494420709',
    projectId: 'imagelabeling-94220',
    storageBucket: 'imagelabeling-94220.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMNPOHg_L8MIJgbiO5PqcbTsTMnhAxn9c',
    appId: '1:573494420709:ios:241a6b305ca2105565600c',
    messagingSenderId: '573494420709',
    projectId: 'imagelabeling-94220',
    storageBucket: 'imagelabeling-94220.firebasestorage.app',
    iosBundleId: 'com.example.imageLabelingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMNPOHg_L8MIJgbiO5PqcbTsTMnhAxn9c',
    appId: '1:573494420709:ios:241a6b305ca2105565600c',
    messagingSenderId: '573494420709',
    projectId: 'imagelabeling-94220',
    storageBucket: 'imagelabeling-94220.firebasestorage.app',
    iosBundleId: 'com.example.imageLabelingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTeDXtXNaQ19PQ3vzg3w43NR3tfItyIb8',
    appId: '1:573494420709:web:4d3dcdb4f18a933b65600c',
    messagingSenderId: '573494420709',
    projectId: 'imagelabeling-94220',
    authDomain: 'imagelabeling-94220.firebaseapp.com',
    storageBucket: 'imagelabeling-94220.firebasestorage.app',
    measurementId: 'G-N4EX97CT8T',
  );
}
